### ISSUE TITLE
`codomain` should be called `range` or `image`

### ISSUE THREAD

**Issue by xplat** [conal/total-map#10]
`codomain` is a word that was coined in order to specifically not mean the thing it means in this library

**Comment by conal** [comment]
Indeed! My apologies for letting this one get by in commit https://github.com/conal/total-map/commit/1ddcabda153a269f3c352ee4ac71ab8b424bdd59.

**Comment by conal** [comment]
I'll change the name to "`range`" and make a new release once there's a [new semiring-num on Hackage](https://github.com/oisdk/semiring-num/issues/5).

**Comment by conal** [comment]
@dmwit Heads up!

**Comment by conal** [comment]
[Released](http://hackage.haskell.org/package/total-map-0.1.3) with `codomain` renamed to "`range`" and `range` deprecated as non-denotative.
