### ISSUE TITLE
Compile error with GHC 8.4.3

### ISSUE THREAD

**Issue by SongWithoutWords** [conal/total-map#8]
I encounter the following compile error when trying to build this package with GHC 8.4.3 with stack on Nixos:

    /run/user/1000/stack-57250010b39a2979/total-map-0.0.6/src/Data/TotalMap.hs:77:10: error:
        * Could not deduce (Semigroup (TMap k v))
            arising from the superclasses of an instance declaration
          from the context: (Ord k, Monoid v)
            bound by the instance declaration at src/Data/TotalMap.hs:77:10-47
        * In the instance declaration for `Monoid (TMap k v)'
       |
    77 | instance (Ord k, Monoid v) => Monoid (TMap k v) where
       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I encountered the same issue when trying to use it as a dependency. Did Semigroup become a superclass of Monoid since this package was last updated?

**Comment by conal** [comment]
Yes, it did. I just tweaked, tested on GHCs 8.0.2, 8.2.2, and 8.4.3, and [released](http://hackage.haskell.org/package/total-map-0.0.7).

**Comment by conal** [comment]
Thanks.
